document.write("<br>");
document.write("  <hr size="2" width="100%"><br>");
document.write("  <center> <i><span");
document.write(" style="color: rgb(51, 51, 255); font-weight: bold;"><a");
document.write(" href="index.htm">Home</a> ~ <a href="michael.htm">Mike</a>");
document.write("~ <a href="suzanne.htm">Suzanne</a> ~ <a");
document.write(" href="amelia.htm">Amelia</a> ~ <a");
document.write(" href="raymond.htm">Raymond</a></span><br");
document.write(" style="font-weight: bold;">");
document.write("  <span style="color: rgb(51, 51, 255); font-weight: bold;"><a");
document.write(" href="portraits.htm">Portraits</a> ~ <a");
document.write(" href="vacations.htm">Vacations</a> ~ <a");
document.write(" href="websites.htm">Websites</a></span></i>");
document.write("  <br style="color: rgb(51, 51, 255);">");
document.write("  <i><span style="color: rgb(51, 51, 255);">Last");
document.write("Updated");
document.write("-- 31 March 2007</span></i> </center>");
document.write("  <br>");
document.write("</head>");
document.write("<body background="lf_edge.jpg">");
document.write("<script src="b.js" type="text/javascript"> </script>");
document.write("<hr size="2" width="100%">*** CONTENT HERE ***<br>");
document.write("<hr size="2" width="100%"><br>");
document.write("<center> <i><span");
document.write(" style="color: rgb(51, 51, 255); font-weight: bold;"><a");
document.write(" href="index.htm">Home</a> ~ <a href="michael.htm">Mike</a>");
document.write("~ <a href="suzanne.htm">Suzanne</a> ~ <a");
document.write(" href="amelia.htm">Amelia</a> ~ <a");
document.write(" href="raymond.htm">Raymond</a></span><br");
document.write(" style="font-weight: bold;">");
document.write("<span style="color: rgb(51, 51, 255); font-weight: bold;"><a");
document.write(" href="portraits.htm">Portraits</a> ~ <a");
document.write(" href="vacations.htm">Vacations</a> ~ <a");
document.write(" href="websites.htm">Websites</a></span></i>");
document.write("<br style="color: rgb(51, 51, 255);">")</center>");
document.write("</body>");