document.write("<table border="0" cellpadding="0" cellspacing="0" width="100%">");
document.write("  <tbody>");
document.write("    <tr>");
document.write("      <td valign="top" width="175"></td>");
document.write("      <td valign="top" width="20"></td>");
document.write("      <td align="center" valign="top"> ");
document.write("        <img alt="The Lewis Library" src="title.gif" height="61" width="545"><br>");
document.write("      </td>");
document.write("    </tr>");
document.write("    <tr>");
document.write("      <td><b><u><font face="Times New Roman,Times"><font color="#ffffff">Quick Links</font></font></u></b> <br>");
document.write("      <b><font face="Times New Roman,Times"><font size="-1"><a href="index.htm"><font color="#ffffff">Home </font><font color="#ffcc99">(Card");
document.write("Catalog)</font></a></font></font></b> <br>");
document.write("      <b><font face="Times New Roman,Times"><font");
document.write(" size="-1"><a href="michael.htm"><font");
document.write(" color="#ffffff">Mike </font><font color="#ffcc99">(Watership");
document.write("Down)</font></a></font></font></b> <br>");
document.write("      <b><font face="Times New Roman,Times"><font");
document.write(" size="-1"><a href="suzanne.htm"><font");
document.write(" color="#ffffff">Suzanne </font><font");
document.write(" color="#ffcc99">(The");
document.write("Lord of Rings)</font></a></font></font></b>");
document.write("      <br>");
document.write("      <b><font face="Times New Roman,Times"><font");
document.write(" size="-1"><a href="amelia.htm"><font");
document.write(" color="#ffffff">Amelia </font><font color="#ffcc99">(Amelia");
document.write("Bedelia)</font></a></font></font></b> <br>");
document.write("      <b><font face="Times New Roman,Times"><font");
document.write(" size="-1"><a href="raymond.htm"><font");
document.write(" color="#ffffff">Raymond </font><font");
document.write(" color="#ffcc99">(Dr.");
document.write("Seuss' ABCs)</font></a></font></font></b>");
document.write("      <br>");
document.write("      <b><font face="Times New Roman,Times"><font");
document.write(" size="-1"><a href="portraits.htm"><font");
document.write(" color="#ffffff">Portraits </font><font");
document.write(" color="#ffcc99">(Art");
document.write("Gallery)</font></a></font></font></b> <br>");
document.write("      <b><font face="Times New Roman,Times"><font");
document.write(" size="-1"><a href="vacations.htm"><font");
document.write(" color="#ffffff">Vacations </font><font");
document.write(" color="#ffcc99">(Map");
document.write("Library)</font></a></font></font></b> <br>");
document.write("      <b><font face="Times New Roman,Times"><font");
document.write(" size="-1"><a href="websites.htm"><font");
document.write(" color="#ffffff">Websites </font><font");
document.write(" color="#ffcc99">(Bookmarks)</font></a></font></font></b>");
document.write("      <br>");
document.write("      <b><font face="Times New Roman,Times"><font");
document.write(" size="-1"><a");
document.write(" href="http://groups.yahoo.com/group/lewis-family/"><font");
document.write(" color="#ffffff">Mailing");
document.write("List </font><font color="#ffcc99">(News Stand)</font></a><br>");
document.write("      <br>");
document.write("      <br>");
document.write("      </font></font></b><font size="-1"><font");
document.write(" face="Times New Roman,Times"><b><br>");
document.write("      </b></font></font><b><u><font");
document.write(" face="Times New Roman,Times"><font color="#ffffff">Contact");
document.write("the Librarians</font></font></u></b> <br>");
document.write("      <b><font face="Times New Roman,Times"><font");
document.write(" size="-1"><a href="mailto:mandslewis@cableone.net"><font");
document.write(" color="#ffcc99">mandslewis@cableone.net</font></a></font></font></b></td>");
document.write("      <td></td>");
document.write("      <td valign="top"><br>");
document.write("      <hr color="blue" size="2" width="100%">");